version: '3.4'

services:
  

  basketdb:
    image: redis:alpine
  catalogdb:
    image: mongo

  discountdb:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4
  
  rabbitmq:
    image: rabbitmq:3-management

  
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount.API/Dockerfile

  datadog-agent:
    image: datadog/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DD_SITE=datadoghq.eu
      - DD_API_KEY=60c2281f62d02fb0013e06e719d100dc

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:

